### ISSUE TITLE
Consider creating a bosh release

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/apt-buildpack#13]
It would be nice if there were a bosh release for this buildpack so I could make it a standard admin buildpack for my users and easily upgrade it regularly.

**Comment by sclevine** [comment]
The CF buildpack BOSH releases are currently only intended for cf-deployment, and the apt-buildpack is an experimental buildpack is not included in cf-deployment.

We ensure that the BOSH releases integrate with the rest of CF before releasing them, so we don't create a BOSH release for every buildpack version, and the BOSH release versions are often behind. If you want to upgrade your buildpacks as soon as new versions are available (instead of having them upgrade automatically when the foundation is upgraded), we recommend using `cf update-buildpack` instead.

**Comment by youngm** [comment]
Thanks @sclevine I didn't notice that the apt-buildpack was still experimental.  Is there a plan for this buildpack to eventually be stabilized and added to cf-deployment?  If so then we can close this issue.  Otherwise,  add my vote as one who would like to see this buildpack eventually added to cf-deployment.  Thanks.

**Comment by sclevine** [comment]
Eventually, yes, along with the new nginx-buildpack.
