### ISSUE TITLE
Future of apt-buildpack with Ubuntu based CF

### ISSUE THREAD

**Issue by mohadipe** [cloudfoundry/apt-buildpack#130]
We use the apt-buildpack in our CF environment with Ubuntu as operating system.
Since Ubuntu is switching from APT to SNAP in future versions. I assume that the apt-buildpack will no longer work with these Ubuntu versions.
Am i correct in my assumption?
Has anyoune dealt with this problem? I would be happy if someone who has had experience with this shares it here.

If something is still unclear about the problem, please ask.

**Comment by robdimsdale** [comment]
@mohadipe can you point us to some documentation from Ubuntu regarding the switch from `apt` to `snap`? This isn't something we've come across, and until we learn more about this it's hard to give any suggestions as to how we would handle it.

**Comment by mohadipe** [comment]
https://www.howtogeek.com/670084/what-you-need-to-know-about-snaps-on-ubuntu-20.04/

> So, with Focal Fossa, Canonical has replaced the Ubuntu Software application with a version that installs snaps by default.

https://wiki.ubuntu.com/FocalFossa/ReleaseNotes

> Snap Store
> The Snap Store (snap-store) replaces ubuntu-software as the default tool for finding and installing packages and snaps.

Ubuntu does not replace apt with snap. https://itsfoss.com/ubuntu-snap-replaces-apt-blueprint/
This seems to have been just an April Fool's joke.

However, I am unsettled by the special case.
Special case for Chromium Browser:
https://ubuntu.com/blog/chromium-in-ubuntu-deb-to-snap-transition
https://askubuntu.com/questions/1185091/why-apt-package-chromium-browser-installs-snap-package-instead

At the moment I don't think this is causing a problem. After what I have found online. But I am still interested in other opinions.

**Comment by robdimsdale** [comment]
Gotcha, thanks for the additional context.

I don't think that installing the chromium browser is a common use-case for web applications, so I think that edge-case is fine.

It sounds like there's no plans for Canonical to drop support for `apt`, which means this buildpack will likely continue in its current form for the foreseeable future. Any future support for snap would likely be in addition to this buildpack, rather than replacing it?

Does that help? Anything else you'd like to know, or can we close this issue?

**Comment by mohadipe** [comment]
Yes from my point of view you can close the ticket. Thank you for your fast response.
But if anyone reads this and has further experience, feel free to contact me.
